"""
Draws the contact email address as SVG outlines, so the site never ships it as
text (not in the HTML, not in the JavaScript bundle) and address harvesters
have nothing to match.

Writes app/content/email-glyphs.ts. The address is an argument, never stored
in the repo:

    uv run --with fonttools --with brotli --with uharfbuzz \
        python -I scripts/email-svg.py someone@example.com

Set in Mona Sans (the site's text face) at weight 500, shaped with HarfBuzz so
kerning matches the browser's.
"""

import sys
from io import BytesIO
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / 'node_modules/@fontsource-variable/mona-sans/files/mona-sans-latin-standard-normal.woff2'
OUT = ROOT / 'app/content/email-glyphs.ts'
AXES = {'wght': 500, 'wdth': 100}

if len(sys.argv) != 2 or '@' not in sys.argv[1]:
    sys.exit('usage: email-svg.py <address>')
address = sys.argv[1]

font = TTFont(FONT)
font.flavor = None  # HarfBuzz reads TrueType, not WOFF2
ttf = BytesIO()
font.save(ttf)
static = instantiateVariableFont(TTFont(BytesIO(ttf.getvalue())), AXES)
glyphs = static.getGlyphSet()
order = static.getGlyphOrder()
upm = static['head'].unitsPerEm
ascent, descent = static['hhea'].ascent, -static['hhea'].descent

# Shape with HarfBuzz (kerning, at the same axis values) on the variable font.
hb_font = hb.Font(hb.Face(hb.Blob(ttf.getvalue())))
hb_font.set_variations(AXES)
buf = hb.Buffer()
buf.add_str(address)
buf.guess_segment_properties()
hb.shape(hb_font, buf, {'kern': True, 'liga': False})

pen = SVGPathPen(glyphs, ntos=lambda n: f'{n:.0f}')
x = 0
for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
    name = order[info.codepoint]
    # Font units are y-up; SVG is y-down, with the baseline at y = 0.
    glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x + pos.x_offset, -pos.y_offset)))
    x += pos.x_advance

OUT.write_text(f'''// Generated by scripts/email-svg.py: the contact email address as SVG outlines.
// Do not put the address in the source as text; regenerate with the script instead.
// Units are Mona Sans font units ({upm} per em); the baseline is y = 0.
export const emailGlyphs = {{
    d: '{pen.getCommands()}',
    width: {x},
    ascent: {ascent},
    descent: {descent},
    unitsPerEm: {upm},
}} as const;
''')
print(f'wrote {OUT.relative_to(ROOT)}: {len(address)} glyphs, {x} units wide')
